<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phplang/scope-exit' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '239b73abe89f9414aa85a7ca075ec9445629192b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phplang/scope-exit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swaggest/json-diff' => array(
            'pretty_version' => 'v3.12.1',
            'version' => '3.12.1.0',
            'reference' => '7ebc4eab95bcc73916433964c266588d09b35052',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swaggest/json-diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swaggest/json-schema' => array(
            'pretty_version' => 'v0.12.43',
            'version' => '0.12.43.0',
            'reference' => '1f3a77a382c5d273a0f1fe34be3b8af4060a88cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swaggest/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
